const fs = require('fs');

const path = 'src/lib/translations.ts';
let content = fs.readFileSync(path, 'utf8');

const terms = {
  'pt-BR': `
    termsConsent1: 'Li e concordo com os ',
    termsLink: 'Termos de Uso',
    termsConsent2: ' e ',
    privacyLink: 'Políticas de Privacidade',
    termsConsent3: ' do Desafio das Estrelas.',
    termsModalTitle: 'Termos de Uso e Privacidade',
    termsModalSub: 'Contrato de Licenciamento SaaS do Mentor',
    termsTechTitle: 'Chancela e Responsabilidade Técnica',
    termsTechDesc: 'O aplicativo Desafio das Estrelas e seus algoritmos de incentivo comportamental são supervisionados pelo Responsável Técnico: Guilherme Carvalho Sinosini (CRP 06/181084).',
    termsSec1Title: '1. Termos de Uso (Terms of Service) e Licenciamento SaaS',
    termsSec1Desc: 'O Desafio das Estrelas concede ao mentor uma licença de uso individual, revogável e não exclusiva de nossa plataforma SaaS (Software as a Service) educacional.',
    termsSec1L1: 'Disponibilidade e SLA: Nossa infraestrutura tecnológica é integrada aos servidores em nuvem do Supabase, usufruindo de acordos de SLA de disponibilidade padrão de mercado de 99,9%, com backups redundantes.',
    termsSec1L2: 'Limites da Licença: O acesso às ferramentas administrativas de mentoria é concedido sob o regime de assinatura. Os limites de crianças cadastradas seguem estritamente o plano ativo escolhido.',
    termsSec1L3: 'Cancelamento: A assinatura pode ser revogada ou alterada a qualquer momento, sem taxas de cancelamento, diretamente no Portal de Pagamento.',
    termsSec2Title: '2. Política de Privacidade (Privacy Policy) e Proteção de Dados',
    termsSec2Desc: 'Respeitamos e protegemos a integridade física, moral e digital dos menores de idade de acordo com a Lei Geral de Proteção de Dados (LGPD) e legislações internacionais:',
    termsSec2L1: 'Anonimização e Segurança: Os dados da criança são protegidos por criptografia em repouso e em trânsito. O aplicativo não requer sobrenomes, documentos ou informações de identificação direta da criança.',
    termsSec2L2: 'Uso Restrito e Não Comercialização: Todas as informações servem exclusivamente para o monitoramento pedagógico da própria família. O aplicativo não monitora, não rastreia, não vende e não compartilha dados das crianças com terceiros.',
    termsSec2L3: 'Relatórios Clínicos: O compartilhamento de dados com psicólogos ou médicos é feito única e exclusivamente sob demanda ativa do mentor, gerando chaves temporárias criptografadas.',
    termsSec3Title: '3. Política de Cookies',
    termsSec3Desc: 'Para garantir conformidade com a LGPD e a GDPR, declaramos que o aplicativo utiliza cookies e tecnologias de armazenamento local estritamente necessários para o funcionamento técnico (sessão, autenticação, idioma), não sendo utilizados para rastreamento comportamental ou fins publicitários.',
    termsSec4Title: '4. Isenção de Responsabilidade Médica (Medical Disclaimer)',
    termsSec4Warning: 'O Desafio das Estrelas é uma ferramenta de suporte ao desenvolvimento comportamental. Os dados gerados não substituem avaliações neurológicas, diagnósticos psiquiátricos ou psicoterapias formais.',
    termsSec4Desc: 'O aplicativo atua como facilitador de rotina familiar baseado na ciência de reforço positivo. A interpretação de dados deve ser feita com fins pedagógicos de incentivo.',
    termsSec5Title: '5. Disposições Finais',
    termsSec5Desc: 'Ao criar a sua conta e utilizar o Desafio das Estrelas, o mentor atesta que é o responsável legal do menor cadastrado e aceita de forma irrevogável todas as regras e políticas descritas neste instrumento.'`,
  'pt-PT': `
    termsConsent1: 'Li e concordo com os ',
    termsLink: 'Termos de Utilização',
    termsConsent2: ' e ',
    privacyLink: 'Políticas de Privacidade',
    termsConsent3: ' do Desafio das Estrelas.',
    termsModalTitle: 'Termos de Utilização e Privacidade',
    termsModalSub: 'Contrato de Licenciamento SaaS do Mentor',
    termsTechTitle: 'Chancela e Responsabilidade Técnica',
    termsTechDesc: 'A aplicação Desafio das Estrelas e os seus algoritmos de incentivo comportamental são supervisionados pelo Responsável Técnico: Guilherme Carvalho Sinosini (CRP 06/181084).',
    termsSec1Title: '1. Termos de Utilização (Terms of Service) e Licenciamento SaaS',
    termsSec1Desc: 'O Desafio das Estrelas concede ao mentor uma licença de uso individual, revogável e não exclusiva da nossa plataforma SaaS educacional.',
    termsSec1L1: 'Disponibilidade e SLA: A nossa infraestrutura tecnológica é integrada aos servidores na nuvem do Supabase, usufruindo de acordos de SLA de disponibilidade padrão de mercado de 99,9%, com backups redundantes.',
    termsSec1L2: 'Limites da Licença: O acesso às ferramentas administrativas de mentoria é concedido sob o regime de assinatura. Os limites de crianças registadas seguem estritamente o plano ativo escolhido.',
    termsSec1L3: 'Cancelamento: A assinatura pode ser revogada ou alterada a qualquer momento, sem taxas de cancelamento, diretamente no Portal de Pagamento.',
    termsSec2Title: '2. Política de Privacidade e Proteção de Dados',
    termsSec2Desc: 'Respeitamos e protegemos a integridade física, moral e digital dos menores de idade de acordo com o RGPD (Regulamento Geral sobre a Proteção de Dados):',
    termsSec2L1: 'Anonimização e Segurança: Os dados da criança são protegidos por criptografia em repouso e em trânsito. A aplicação não requer apelidos, documentos ou informações de identificação direta da criança.',
    termsSec2L2: 'Uso Restrito e Não Comercialização: Todas as informações servem exclusivamente para a monitorização pedagógica da própria família. A aplicação não monitoriza, não rastreia, não vende e não partilha dados das crianças com terceiros.',
    termsSec2L3: 'Relatórios Clínicos: A partilha de dados com psicólogos ou médicos é feita única e exclusivamente sob demanda ativa do mentor, gerando chaves temporárias criptografadas.',
    termsSec3Title: '3. Política de Cookies',
    termsSec3Desc: 'Para garantir conformidade com o RGPD, declaramos que a aplicação utiliza cookies e tecnologias de armazenamento local estritamente necessários para o funcionamento técnico (sessão, autenticação, idioma), não sendo utilizados para rastreio comportamental ou fins publicitários.',
    termsSec4Title: '4. Isenção de Responsabilidade Médica (Medical Disclaimer)',
    termsSec4Warning: 'O Desafio das Estrelas é uma ferramenta de suporte ao desenvolvimento comportamental. Os dados gerados não substituem avaliações neurológicas, diagnósticos psiquiátricos ou psicoterapias formais.',
    termsSec4Desc: 'A aplicação atua como facilitador de rotina familiar baseado na ciência de reforço positivo. A interpretação de dados deve ser feita com fins pedagógicos de incentivo.',
    termsSec5Title: '5. Disposições Finais',
    termsSec5Desc: 'Ao criar a sua conta e utilizar o Desafio das Estrelas, o mentor atesta que é o responsável legal do menor registado e aceita de forma irrevogável todas as regras e políticas descritas neste instrumento.'`,
  'en': `
    termsConsent1: 'I have read and agree to the ',
    termsLink: 'Terms of Use',
    termsConsent2: ' and ',
    privacyLink: 'Privacy Policies',
    termsConsent3: ' of Star Challenge.',
    termsModalTitle: 'Terms of Use and Privacy',
    termsModalSub: 'Mentor SaaS Licensing Agreement',
    termsTechTitle: 'Technical Endorsement and Responsibility',
    termsTechDesc: 'The Star Challenge app and its behavioral incentive algorithms are supervised by Technical Manager: Guilherme Carvalho Sinosini (CRP 06/181084).',
    termsSec1Title: '1. Terms of Service and SaaS Licensing',
    termsSec1Desc: 'Star Challenge grants the mentor an individual, revocable, and non-exclusive license to use our educational SaaS (Software as a Service) platform.',
    termsSec1L1: 'Availability and SLA: Our technology infrastructure is integrated with Supabase cloud servers, enjoying standard market availability SLA agreements of 99.9%, with redundant backups.',
    termsSec1L2: 'License Limits: Access to administrative mentoring tools is granted on a subscription basis. Registered children limits strictly follow the chosen active plan.',
    termsSec1L3: 'Cancellation: The subscription can be revoked or changed at any time, without cancellation fees, directly on the Payment Portal.',
    termsSec2Title: '2. Privacy Policy and Data Protection',
    termsSec2Desc: 'We respect and protect the physical, moral, and digital integrity of minors in accordance with GDPR and international laws:',
    termsSec2L1: 'Anonymization and Security: Child data is protected by encryption at rest and in transit. The application does not require surnames, documents, or direct identification information of the child.',
    termsSec2L2: 'Restricted Use and Non-Commercialization: All information serves exclusively for the pedagogical monitoring of the family itself. The app does not monitor, track, sell, or share children\\'s data with third parties.',
    termsSec2L3: 'Clinical Reports: Sharing data with psychologists or doctors is done solely and exclusively upon active demand from the mentor, generating temporary encrypted keys.',
    termsSec3Title: '3. Cookies Policy',
    termsSec3Desc: 'To ensure GDPR compliance, we declare that the app uses cookies and local storage technologies strictly necessary for technical operation (session, authentication, language), not used for behavioral tracking or advertising purposes.',
    termsSec4Title: '4. Medical Disclaimer',
    termsSec4Warning: 'Star Challenge is a support tool for behavioral development. The data generated does not replace neurological evaluations, psychiatric diagnoses, or formal psychotherapies.',
    termsSec4Desc: 'The app acts as a family routine facilitator based on the science of positive reinforcement. Data interpretation must be done for pedagogical incentive purposes.',
    termsSec5Title: '5. Final Provisions',
    termsSec5Desc: 'By creating an account and using Star Challenge, the mentor attests that they are the legal guardian of the registered minor and irrevocably accepts all rules and policies described in this instrument.'`,
  'es': `
    termsConsent1: 'He leído y acepto los ',
    termsLink: 'Términos de Uso',
    termsConsent2: ' y las ',
    privacyLink: 'Políticas de Privacidad',
    termsConsent3: ' del Desafío de las Estrellas.',
    termsModalTitle: 'Términos de Uso y Privacidad',
    termsModalSub: 'Acuerdo de Licencia SaaS para Mentores',
    termsTechTitle: 'Respaldo y Responsabilidad Técnica',
    termsTechDesc: 'La aplicación Desafío de las Estrellas y sus algoritmos de incentivo conductual están supervisados por el Gerente Técnico: Guilherme Carvalho Sinosini (CRP 06/181084).',
    termsSec1Title: '1. Términos de Servicio y Licencia SaaS',
    termsSec1Desc: 'Desafío de las Estrellas otorga al mentor una licencia individual, revocable y no exclusiva para usar nuestra plataforma educativa SaaS (Software como Servicio).',
    termsSec1L1: 'Disponibilidad y SLA: Nuestra infraestructura tecnológica está integrada con los servidores en la nube de Supabase, disfrutando de acuerdos de SLA de disponibilidad estándar del mercado del 99,9%, con copias de seguridad redundantes.',
    termsSec1L2: 'Límites de la Licencia: El acceso a las herramientas administrativas de mentoría se otorga mediante suscripción. Los límites de niños registrados siguen estrictamente el plan activo elegido.',
    termsSec1L3: 'Cancelación: La suscripción puede ser revocada o modificada en cualquier momento, sin cargos por cancelación, directamente en el Portal de Pagos.',
    termsSec2Title: '2. Política de Privacidad y Protección de Datos',
    termsSec2Desc: 'Respetamos y protegemos la integridad física, moral y digital de los menores de acuerdo con el GDPR y las leyes internacionales:',
    termsSec2L1: 'Anonimato y Seguridad: Los datos del niño están protegidos por encriptación en reposo y en tránsito. La aplicación no requiere apellidos, documentos o información de identificación directa del niño.',
    termsSec2L2: 'Uso Restringido y No Comercialización: Toda la información sirve exclusivamente para el seguimiento pedagógico de la propia familia. La aplicación no monitoriza, rastrea, vende ni comparte datos de niños con terceros.',
    termsSec2L3: 'Informes Clínicos: Compartir datos con psicólogos o médicos se realiza única y exclusivamente bajo demanda activa del mentor, generando claves cifradas temporales.',
    termsSec3Title: '3. Política de Cookies',
    termsSec3Desc: 'Para asegurar el cumplimiento del GDPR, declaramos que la aplicación utiliza cookies y tecnologías de almacenamiento local estrictamente necesarias para el funcionamiento técnico (sesión, autenticación, idioma), no utilizadas para seguimiento de comportamiento o fines publicitarios.',
    termsSec4Title: '4. Descargo de Responsabilidad Médica (Medical Disclaimer)',
    termsSec4Warning: 'Desafío de las Estrellas es una herramienta de apoyo para el desarrollo conductual. Los datos generados no reemplazan las evaluaciones neurológicas, los diagnósticos psiquiátricos o las psicoterapias formales.',
    termsSec4Desc: 'La aplicación actúa como un facilitador de la rutina familiar basado en la ciencia del refuerzo positivo. La interpretación de datos debe realizarse con fines pedagógicos de incentivo.',
    termsSec5Title: '5. Disposiciones Finales',
    termsSec5Desc: 'Al crear una cuenta y usar Desafío de las Estrellas, el mentor certifica que es el tutor legal del menor registrado y acepta irrevocablemente todas las reglas y políticas descritas en este instrumento.'`,
  'fr': `
    termsConsent1: 'J\\'ai lu et j\\'accepte les ',
    termsLink: 'Conditions d\\'Utilisation',
    termsConsent2: ' et la ',
    privacyLink: 'Politique de Confidentialité',
    termsConsent3: ' du Défi des Étoiles.',
    termsModalTitle: 'Conditions d\\'Utilisation et Confidentialité',
    termsModalSub: 'Accord de Licence SaaS pour Mentors',
    termsTechTitle: 'Approbation et Responsabilité Technique',
    termsTechDesc: 'L\\'application Défi des Étoiles et ses algorithmes d\\'incitation comportementale sont supervisés par le Responsable Technique : Guilherme Carvalho Sinosini (CRP 06/181084).',
    termsSec1Title: '1. Conditions de Service et Licence SaaS',
    termsSec1Desc: 'Le Défi des Étoiles accorde au mentor une licence individuelle, révocable et non exclusive d\\'utilisation de notre plateforme éducative SaaS.',
    termsSec1L1: 'Disponibilité et SLA : Notre infrastructure technologique est intégrée aux serveurs cloud Supabase, bénéficiant d\\'accords SLA de disponibilité standard de 99,9%, avec des sauvegardes redondantes.',
    termsSec1L2: 'Limites de Licence : L\\'accès aux outils de mentorat est accordé sur la base d\\'un abonnement. Les limites d\\'enfants inscrits suivent strictement le plan actif choisi.',
    termsSec1L3: 'Annulation : L\\'abonnement peut être révoqué ou modifié à tout moment, sans frais, directement sur le portail de paiement.',
    termsSec2Title: '2. Politique de Confidentialité et Protection des Données',
    termsSec2Desc: 'Nous respectons et protégeons l\\'intégrité physique, morale et numérique des mineurs conformément au RGPD et aux lois internationales :',
    termsSec2L1: 'Anonymat et Sécurité : Les données des enfants sont protégées par cryptage au repos et en transit. L\\'application n\\'exige pas de nom de famille, de documents ou d\\'informations d\\'identification directe.',
    termsSec2L2: 'Utilisation Restreinte : Toutes les informations servent exclusivement au suivi pédagogique de la famille. L\\'application ne surveille pas, ne suit pas, ne vend pas et ne partage pas les données des enfants.',
    termsSec2L3: 'Rapports Cliniques : Le partage de données avec des psychologues n\\'est fait qu\\'à la demande active du mentor, en générant des clés cryptées temporaires.',
    termsSec3Title: '3. Politique des Cookies',
    termsSec3Desc: 'Pour garantir la conformité au RGPD, nous déclarons que l\\'application utilise des cookies strictement nécessaires au fonctionnement technique (session, authentification, langue), sans suivi comportemental.',
    termsSec4Title: '4. Clause de Non-responsabilité Médicale',
    termsSec4Warning: 'Le Défi des Étoiles est un outil de soutien au développement comportemental. Les données générées ne remplacent pas les évaluations neurologiques ou psychiatriques formelles.',
    termsSec4Desc: 'L\\'application agit comme facilitateur de routine familiale basé sur le renforcement positif. L\\'interprétation des données doit se faire à des fins incitatives pédagogiques.',
    termsSec5Title: '5. Dispositions Finales',
    termsSec5Desc: 'En créant un compte, le mentor atteste être le tuteur légal du mineur inscrit et accepte irrévocablement toutes les règles décrites dans cet instrument.'`,
  'it': `
    termsConsent1: 'Ho letto e accetto i ',
    termsLink: 'Termini di Utilizzo',
    termsConsent2: ' e le ',
    privacyLink: 'Politiche sulla Privacy',
    termsConsent3: ' della Sfida delle Stelle.',
    termsModalTitle: 'Termini di Utilizzo e Privacy',
    termsModalSub: 'Accordo di Licenza SaaS per Mentor',
    termsTechTitle: 'Responsabilità Tecnica',
    termsTechDesc: 'L\\'app Sfida delle Stelle e i suoi algoritmi comportamentali sono supervisionati dal Responsabile Tecnico: Guilherme Carvalho Sinosini (CRP 06/181084).',
    termsSec1Title: '1. Termini di Servizio e Licenza SaaS',
    termsSec1Desc: 'La Sfida delle Stelle concede al mentor una licenza individuale, revocabile e non esclusiva per l\\'uso della nostra piattaforma SaaS educativa.',
    termsSec1L1: 'Disponibilità e SLA: La nostra infrastruttura tecnologica è integrata con i server cloud Supabase, con SLA di disponibilità standard del mercato del 99,9% e backup ridondanti.',
    termsSec1L2: 'Limiti di Licenza: L\\'accesso agli strumenti amministrativi è concesso su abbonamento. I limiti dei bambini registrati seguono il piano attivo scelto.',
    termsSec1L3: 'Cancellazione: L\\'abbonamento può essere revocato in qualsiasi momento, senza penali, direttamente nel Portale dei Pagamenti.',
    termsSec2Title: '2. Informativa sulla Privacy e Protezione dei Dati',
    termsSec2Desc: 'Rispettiamo e proteggiamo l\\'integrità dei minori in conformità con il GDPR e le leggi internazionali:',
    termsSec2L1: 'Anonimato e Sicurezza: I dati del bambino sono protetti da crittografia. L\\'app non richiede cognomi o informazioni di identificazione diretta.',
    termsSec2L2: 'Uso Ristretto: Tutte le informazioni servono esclusivamente al monitoraggio pedagogico della famiglia. L\\'app non condivide, vende o traccia i dati dei bambini con terzi.',
    termsSec2L3: 'Referti Clinici: La condivisione dei dati con professionisti della salute avviene esclusivamente su richiesta attiva del mentor, generando chiavi crittografate temporanee.',
    termsSec3Title: '3. Politica sui Cookie',
    termsSec3Desc: 'L\\'applicazione utilizza cookie e archiviazione locale strettamente necessari per il funzionamento tecnico (sessione, lingua), senza fini pubblicitari o di tracciamento.',
    termsSec4Title: '4. Esclusione di Responsabilità Medica',
    termsSec4Warning: 'La Sfida delle Stelle è uno strumento di supporto comportamentale. I dati generati non sostituiscono valutazioni neurologiche, psichiatriche o psicoterapie formali.',
    termsSec4Desc: 'L\\'app agisce come facilitatore della routine basato sul rinforzo positivo. L\\'interpretazione dei dati è a fini pedagogici.',
    termsSec5Title: '5. Disposizioni Finali',
    termsSec5Desc: 'Creando un account, il mentor attesta di essere il tutore legale del minore e accetta irrevocabilmente tutte le regole descritte in questo strumento.'`,
  'zh': `
    termsConsent1: '我已阅读并同意星际挑战的',
    termsLink: '使用条款',
    termsConsent2: '和',
    privacyLink: '隐私政策',
    termsConsent3: '。',
    termsModalTitle: '使用条款和隐私政策',
    termsModalSub: '导师 SaaS 许可协议',
    termsTechTitle: '技术认可和责任',
    termsTechDesc: '星际挑战应用及其行为激励算法由技术经理 Guilherme Carvalho Sinosini（CRP 06/181084）监督。',
    termsSec1Title: '1. 服务条款和 SaaS 许可',
    termsSec1Desc: '星际挑战授予导师个人、可撤销和非排他性的许可，以使用我们的教育 SaaS 平台。',
    termsSec1L1: '可用性和 SLA：我们的技术基础设施与 Supabase 云服务器集成，享有 99.9% 的市场标准 SLA，并具有冗余备份。',
    termsSec1L2: '许可限制：导师管理工具的访问基于订阅计划。',
    termsSec1L3: '取消：您可以随时在支付门户上取消或更改订阅，无需取消费用。',
    termsSec2Title: '2. 隐私政策和数据保护',
    termsSec2Desc: '我们根据 GDPR 和国际法律尊重并保护未成年人的数字隐私：',
    termsSec2L1: '匿名和安全：儿童数据在存储和传输时均受加密保护。该应用不需要儿童的姓氏或直接身份信息。',
    termsSec2L2: '限制使用和非商业化：所有信息仅用于家庭的内部教学监控。该应用绝不监控、跟踪、出售或与第三方共享儿童数据。',
    termsSec2L3: '临床报告：只有在导师主动要求时，才会生成临时加密密钥以与心理学家分享数据。',
    termsSec3Title: '3. Cookie 政策',
    termsSec3Desc: '该应用程序仅使用技术运行所需的 Cookie（登录会话、身份验证、语言），绝不用于行为跟踪或广告目的。',
    termsSec4Title: '4. 医疗免责声明',
    termsSec4Warning: '星际挑战是行为发展的支持工具。生成的数据不替代神经学评估或正式心理治疗。',
    termsSec4Desc: '该应用程序是基于积极强化科学的家庭常规辅助工具。数据的解释仅用于教育目的。',
    termsSec5Title: '5. 最终条款',
    termsSec5Desc: '创建帐户即表示导师证明其为未成年人的合法监护人，并不可撤销地接受本协议中的所有规则。'`
};

for (const lang of Object.keys(terms)) {
  const marker = \`'\${lang}': {\`;
  const insertIndex = content.indexOf(marker);
  if (insertIndex !== -1) {
    const nextLineIndex = content.indexOf('\\n', insertIndex) + 1;
    content = content.slice(0, nextLineIndex) + terms[lang] + ',' + content.slice(nextLineIndex);
  }
}

fs.writeFileSync(path, content, 'utf8');
console.log('Translations updated successfully!');
